# This is a basic Jest workflow that is automatically triggered

name: Lint and run Jest Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_call:
    push:
        branches:
            - '*'
            - '!main'
    pull_request:
        branches:
            - '*'
            - '!main'

jobs:
    configure-node:
        runs-on: ubuntu-latest
        steps:
            - name: âš™ï¸ Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org'

            - name: âš™ï¸ Inspect NPM & Node Version
              run: |
                  echo Node Version: `node --version`
                  echo NPM Version: `npm --version`

            - name: Install dependencies
              run: npm install --quiet

    lint-code:
        runs-on: ubuntu-latest
        needs: [configure-node]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - name: ğŸ§¼ Run Linter
              run: |
                  npm run lint
    jest-test:
        runs-on: ubuntu-latest
        needs: [configure-node, lint-code]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - name: ğŸ§ª Run Jest Tests
              run: npm test

    test-build:
        runs-on: ubuntu-latest
        needs: [configure-node, jest-test]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}

            - name: ğŸ”¨ Check build success
              run: npm run build
